### ISSUE TITLE
How start IP Monitor

### ISSUE THREAD

**Issue by rudacabu** [pupi1985/IPMonitor#12]
Hi, sorry for the question Im new at this.

I download the program but I dont really know how to started, can you help me

**Comment by pupi1985** [comment]
Please, click the start button on the main screen

**Comment by rudacabu** [comment]
That is presisely my question, which is the file to open the main scream, the foow is what Im seeing when I download

![image](https://user-images.githubusercontent.com/36646105/36430328-ec1f91a4-1622-11e8-941c-5ec7b5d1795d.png)

**Comment by pupi1985** [comment]
As stated in the [Requirements](https://github.com/pupi1985/IPMonitor#requirements) section, you need to have Java 7+ installed. Then just execute the IPMonitor.jar file.

Note that is a question about Windows and Java rather than IPMonitor. You can search for additional help in this link: https://www.google.com.ar/search?q=how+to+run+java+applications+in+windows&oq=how+to+run+java+applications+in+windows
