### ISSUE TITLE
Feature request: notifications for uptime, last login, last logout, last sleep etc.

### ISSUE THREAD

**Issue by JayBrown** [pupi1985/IPMonitor#3]
I've installed the IP Monitor for friends/family on two Windows 10 machines, after another friend received mail from a copyright troll, and there was a technical error, and the IP address they used was the wrong one.

So IP Monitor is great to prove your innocence in these cases, even if they're pretty rare. As an addition it would also be nice to know, when the computer was active, and when it was shut down or in sleep mode etc.… for situations in which the IP address is correct, but you weren't around, and another person/computer in your network did the copyright infringement.

These would be notifications options like:

```
%UPTIME%
%LASTLOGIN%
%LASTLOGOUT%
%LASTSLEEP%
%LASTWAKE%
%LASTSCREENSLEEP%
%LASTSCREENWAKE%
```

Screen sleep options should include screen saver on/off. Login/logout should include boot/reboot and shutdown/logout-to-reboot plus user-switching.

**Comment by pupi1985** [comment]
Hi Jay,

I'm happy to know this tool is useful for someone out there :)

I think your feature request is well fundamented. However, I it is assuming IP Monitor is an activity monitor rather than an IP address monitoring tool. As that would change the very essence of IP Monitor I'd rather not work on that.

Thanks again for your time.
