### ISSUE TITLE
Not working after some system updates (Ubuntu 16.04)

### ISSUE THREAD

**Issue by haoanw** [pupi1985/IPMonitor#5]
Thanks for your contribution. I've been using this software to monitoring my home desktop, my public ip changes every time when a power loss occur. Even without login into the system, the daemon will sent email notification and it worked fine for several days until i've done some updates with the Ubuntu (16.04), then it stop working and some times even cant start the daemon (but still can be installed). Not sure what conflict i have here. Probably you may give me some hints. I am using the version in sourceforge and been directed to here.

This is a great tool, it really deserves more people's attention.

**Comment by pupi1985** [comment]
Honestly, if you tell me it used to work and, after some system updates, now it sometimes doesn't, really, there isn't much I can do. It is like expecting a diagnosis from a doctor after telling them "My head hurts and it didn't yesterday" :)

It would have been better if it never worked rather than sometimes. In fact, I'd double check if the daemon isn't actually starting (maybe it was already started before). Make sure you have the appropriate permissions. Check the logs. Check the wiki: https://github.com/pupi1985/IPMonitor/wiki/Troubleshooting

Is it working on a clean install of Ubuntu 16.04?

There are a lot of info missing. Most likely, the troubleshooting section in the wiki will show you the reason why it isn't working. Anyway, the more you can isolate the changes you did on the system, the better. Let me know how it goes.

**Comment by pupi1985** [comment]
Closed due to lack of feedback.

**Comment by haoanw** [comment]
sorry for the late reply, everything works again after a fresh download and re-configuration. thanks for you reply and help!
